server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: categoria-service
          uri: lb://categoria-service
          predicates:
            - Path=/api/categorias/**

        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/api/productos/**

        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/api/clientes/**

        - id: pedido-service
          uri: lb://pedido-service
          predicates:
            - Path=/api/pedidos/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka